### ISSUE TITLE
multithreading issue

### ISSUE THREAD

**Issue by jcageman** [VSZue/DonAINavigation#1]
Hi,

I am using your fantastic navigation system and found one issue with it. When using the multi-threading option it hangs very frequently. When using one bot i have no issue, but as soon as i have 4-8 bots i get the very frequent problem of hangs (stalls for sometimes 1 sec, but could also be 1 minute). When deactivating the multi-threading option everything works smooth. It seems to deadlock on the abort task, at least that is where i am always at when i pause the debugger during these hangs.

A few important things that might make this case special:
- I use the ForceRescheduleOption
- I force my task to abort after 4 sec's, since my game is very fast paced and path finding has to adjust frequently. I use a time limit decorator on the fly to node.

Thanks for all your efforts. For now i have a workaround so the priority to me isn't very high.

Kind regards,
Cageman

**Comment by VSZue** [comment]
Hey, thanks for reporting this issue!

I feared as much, that's why I disabled multi-threading by default. My knowledge of concurrency in C++/Unreal is limited and there may well be edge cases like these that I didn't consider.

I'll take a look at this if/when multi-threading becomes important in my own game. So far it hasn't been necessary for me, but we'll see how it goes.

Thanks again for creating an issue for this, makes it so much easier to track for me!
